services:
  - type: web
    name: calzados-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn calzados_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: "calzados_db"
      - key: DB_USER
        value: "root"
      - key: DB_PASSWORD
        value: "tu_password"
      - key: DB_HOST
        value: "tu-host-db"
      - key: DB_PORT
        value: "3306"
      - key: SECRET_KEY
        value: "tu_clave_secreta_produccion"
